name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: 2c0f6a4048d2e2e920c080669ed5ca9e8067abc1
        with:
          args: >
            -Dsonar.projectKey=DZ-Sim_Assignment-2_Sonarqube_OWASP-NodeGoat
            -Dsonar.organization=dz-sim